{
 "title": "Error budget",
 "time": { "from": "now-6h", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "sni",
    "query": {
     "query": "label_values(service:sli_seconds:total:percent{}, sni)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hour",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-service:sli_seconds:total:percent{term=\"hour\", sni=~\"$sni\", kind=\"active_failed\"}) * 100"
    }
   ]
  },
  {
   "title": "Day",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "repeat": "interval",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-service:sli_seconds:total:percent{term=\"day\", sni=~\"$sni\", kind=\"active_failed\"}) * 100"
    }
   ]
  },
  {
   "title": "Week",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-service:sli_seconds:total:percent{term=\"week\", sni=~\"$sni\", kind=\"active_failed\"}) * 100"
    }
   ]
  },
  {
   "title": "Calendar Month",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-service:sli_seconds:total:percent{term=\"calendarmonth\", sni=~\"$sni\", kind=\"active_failed\"}) * 100"
    }
   ]
  },
  {
   "title": "Error Budget (hourly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-service:sli_seconds:total:percent{term=\"hour\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{sni}}:{{term}}"
    },
    { "expr": "vector(99.95)", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Error Budget (daily)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-service:sli_seconds:total:percent{term=\"day\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{sni}}:{{term}}"
    },
    { "expr": "vector(99.95)", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Error Budget (weekly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-service:sli_seconds:total:percent{term=\"week\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{sni}}:{{term}}"
    },
    { "expr": "vector(99.95)", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Error Budget (monthly)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-service:sli_seconds:total:percent{term=\"calendarmonth\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{sni}}:{{term}}"
    },
    { "expr": "vector(99.95)", "legendFormat": "SLO" }
   ]
  },
  { "title": "Explore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Error Budget (daily)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-service:sli_seconds:total:percent{term=\"day\", sni=~\"$sni\", kind=\"active_failed\"}) * 100",
     "legendFormat": "{{sni}}:{{term}}"
    },
    { "expr": "vector(99.95)", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "Failed Seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed Seconds by Node",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max by (pod) (connectivity_exporter_seconds_total{sni=~\"$sni\", kind=\"active_failed\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}